spring:
  rabbitmq:
    addresses: localhost
    username: kpi
    password: kpi
    virtual-host: kpi
metrics:
  start:
    exchange: processor-exchange
  finalize:
    exchange: completed-exchange
  redis:
    host: localhost
    port: 6379