rabbitmq:
  image: rabbitmq:3.6.9-management-alpine
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_VHOST: kpi
    RABBITMQ_DEFAULT_PASS: kpi
    RABBITMQ_DEFAULT_USER: kpi
